### ISSUE TITLE
support for BLKCLOSEZONE should be required

### ISSUE THREAD

**Issue by inikep** [westerndigitalcorporation/libzbd#12]
BLKCLOSEZONE requires uapi headers from linux v5.5+.
The latest Ubuntu 20.04.3 LTS has only linux-libc-dev version (5.4.0-89.100).
IMHO it doesn't make sense to compile libzbd without BLKCLOSEZONE because it doesn't work correctly. It would be better to stop configure or building with an error message that 5.5+ is required.

**Comment by inikep** [comment]
I and Aravind Ramesh spent a lot of time trying to figure out why sysbench is not working with MySQL+RocksDB+zenfs on the latest Ubuntu 20.04.3 LTS. I'm affraid that many users may encounter the same issue.

**Comment by damien-lemoal** [comment]
What is sysbench ? If it is part of RocksDB+zenfs, then these must check for 5.5+ zone API at compile time. Ubuntu with 5.4 kernel does not support NVMe ZNS anyway. So all of this is not a libzbd problem. It is an application system integration problem.

use Fedora and these problems go away…

**Comment by inikep** [comment]
The latest Ubuntu 20.04.3 LTS has kernel 5.11 but only linux-libc-dev version (5.4.0-89.100) what means that `blkzoned.h` is from 5.4 and doesn't support `BLKCLOSEZONE`.
I agree that this is a mistake from Ubuntu but users should be notified that `blkzoned.h` doesn't match their 5.11 kernel.

**Comment by inikep** [comment]
OK, I will create an issue for `zenfs`.
