### ISSUE TITLE
Functions not exported

### ISSUE THREAD

**Issue by lewisxy** [westerndigitalcorporation/libzbd#14]
I am not sure if it's intentional, but the only functions that are exported appear to be those defined in [`exports`](https://github.com/westerndigitalcorporation/libzbd/blob/master/lib/exports). `zbd_get_info` does not appear to be exported, as I got an undefined reference error when trying to use it.

**Comment by damien-lemoal** [comment]
Yep. It was misnamed zbd_get_device_info... Just pushed a patch fixing this. Please check.

**Comment by lewisxy** [comment]
It works, thanks.
