### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [westerndigitalcorporation/libzbd#18]
I would like to point out that identifiers like “[`_LIBZBD_H_`](https://github.com/westerndigitalcorporation/libzbd/blob/a8a66e70be7579e2f84b9dc424040dd2c57fd044/include/libzbd/zbd.h#L10 "Update candidate")” and “[`__GZVIEWER_H__`](https://github.com/westerndigitalcorporation/libzbd/blob/6a1cbff448e3fcd700a9ddf8d97092f2bcb105de/tools/viewer/gzbd_viewer.h#L7 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by damien-lemoal** [comment]
Not critical, but you can send a patch if you want to fix that.

**Comment by elfring** [comment]
🔮 Will other contributors be quicker to fix affected source code?
