### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [westerndigitalcorporation/libzbd#19]
Would you like to [add](https://github.com/westerndigitalcorporation/libzbd/commit/6a1cbff448e3fcd700a9ddf8d97092f2bcb105de "tools: gui: add pthread library") the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/westerndigitalcorporation/libzbd/blob/16e42aeeeae06f02a7441a7d1fa729d910f724cc/configure.ac#L62 "Update candidate")?

**Comment by damien-lemoal** [comment]
No. ax pthread is part of autoconf-archive which causes issues with some distros. So not re-adding it.
