### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [westerndigitalcorporation/libzbd#20]
The function “[printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I find that the implementation of the function “[dz_sig_handler](https://github.com/westerndigitalcorporation/libzbd/blob/06e9a70d2d50471d4325e54eebafc04bfdecc832/tools/gui/gzbd.c#L49 "Update candidate")” should be adjusted.

**Comment by damien-lemoal** [comment]
Fixed.

**Comment by elfring** [comment]
:thinking: Would you like to [take further software design options into account](https://github.com/westerndigitalcorporation/libzbd/commit/baa93883f2efec5207af4e7287051490c4ca9e66 "Change for dz_sig_handler()")?
