### ISSUE TITLE
zbd: error while loading shared libraries: libzbd.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PengJasper** [westerndigitalcorporation/libzbd#23]
zbd: error while loading shared libraries: libzbd.so.2: cannot open shared object file: No such file or directory

**Comment by damien-lemoal** [comment]
If you want help, please provide more information. I cannot do anything only based on an error message. What did you do to get this ? Did you run ldconfig after compiling & installing ?
