### ISSUE TITLE
Is libzbd compatible with SMR HDD(Ultrastar DC HC670 26TB)

### ISSUE THREAD

**Issue by sg20180546** [westerndigitalcorporation/libzbd#26]
Hello. im ZNS SSD researcher.
for the purpose of extending my work for SMR HDD, is libzbd compatible with westerndigital Ultrastar DC HC670?
Otherwise, If i should use libzb"c" for SMR HDD.
thank you.

**Comment by MatiasBjorling** [comment]
Hi,

Yep, libzbd works for both ZNS and SMR HDDs. It uses the general zoned API exposed by the kernel.

**Comment by sg20180546** [comment]
thank you so much !!!
