### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by Rishabh4275** [westerndigitalcorporation/libzbd#4]
Hello,

We are looking to add zbd support to Ceph, for which we consume this package(libzbd).
Thus, the Ceph team requires a Debian package of the libzbd package for its distribution. 
Would it be possible to have a Debian package for this repository, and have it added to the Debian repository.

I looked at creating a Debian package using debmake in Ubuntu 20.x using the document: 
https://www.debian.org/doc/manuals/debmake-doc/index.en.html

While following the steps present in the document, I was able to install zbd on my system using the created deb package. 
It requires a lot of information to be added to be compliant with the Debian repository policies:  https://www.debian.org/doc/devel-manuals#policy.
The details that need to be added are also present in the debmake tutorial linked above. 

Would it be possible to create and add the Debian package to the Debian repository. 
Would appreciate your help and I would be happy to extend my support wherever required. 

Thank you.

Regards,
Rishabh

**Comment by damien-lemoal** [comment]
Sure, no problem. We can work on this. Can you send me patches for what you already have ? That would avoid me to redo what you have done already. I will fill in the missing parts needed.

**Comment by Rishabh4275** [comment]
Thank you.
So, I wanted to discuss my approach for starters, do you want a script that does the Debian folder creation and modifications as needed, or do you want the actual Debian folder in the repository itself.

**Comment by damien-lemoal** [comment]
Send a patch PR with what you have. I think that is easier.
You can send me the patches by email directly too if that is easier for you.

**Comment by Rishabh4275** [comment]
Sure, I will send it today. 
Thank you.

**Comment by Rishabh4275** [comment]
I've created a PR with a script that would create a deb package. 
The created debian folder can be seen at: https://github.com/Rishabh4275/libzbd/tree/debian
The changes that would be required to the debian folder according to : https://www.debian.org/doc/manuals/debmake-doc/index.en.html

1. Remove all comments
Files:
2. Watch: Remove Comment
3. Rules: Remove Comments - This is used for build
4. Copyright: Update License and Copyright as mentioned below
5.  Control:
5.1 Section: embedded
5.2 Maintainer: <Please fill value>
5.3 Homepage : <URL> <Please fill value>
6. Changelog: <Please fill value>
7. README.Debian: Should this be different from standard README?
8. patches/series: Remove Comment
9. source/local-options: Remove Comments


Please mention any updates as necessary.

**Comment by damien-lemoal** [comment]
Thanks. I have done something similar but refined it to generate binary, devel and dbg packages and integrated into Makefile.am. I pushed what I have in the staging branch. Can you check please ?

You need to run:
```
./configure --enable-deb
make deb
```

And you will get 3 .deb packages. I tested the build on Fedora and it works. I do not have a Debian system to test the installation of the packages. Please try.

**Comment by Rishabh4275** [comment]
Thank you @damien-lemoal. Testing it in Ubuntu 20.04.1. It works.

**Comment by Rishabh4275** [comment]
I think the next step would be to get it added to the Debian repository. I will look up the possible steps and add them here.

**Comment by damien-lemoal** [comment]
OK. Great. Thanks for checking. I will do another round of checks & test and push to master branch. I am closing this issue and your PR too. Thanks !
